# Generated by Django 5.2.8 on 2026-05-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_notification_is_delivered"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
