# Generated by Django 5.2.8 on 2026-05-06 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="servicerequest",
            name="location",
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="collector",
            field=models.ForeignKey(
                limit_choices_to={"role": "COLLECTOR"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="location_details",
            field=models.TextField(
                default="", help_text="Specific address or landmarks"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="agreed_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="subscription",
            name="collector",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "COLLECTOR"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="customer_type",
            field=models.CharField(
                choices=[
                    ("HOME", "Home"),
                    ("BUILDING", "Building"),
                    ("COMPANY", "Company"),
                    ("INSTITUTION", "Institution"),
                    ("SHOP", "Shop"),
                    ("RESTAURANT", "Restaurant"),
                    ("HOTEL", "Hotel"),
                    ("OTHER", "Other"),
                ],
                default="HOME",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("DAILY", "Daily"),
                    ("WEEKLY", "Weekly"),
                    ("BIWEEKLY", "Bi-Weekly"),
                    ("MONTHLY", "Monthly"),
                    ("CUSTOM", "Custom"),
                ],
                default="WEEKLY",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectors",
                        to="collection.district",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "manager",
                    models.ForeignKey(
                        limit_choices_to={"role": "LOCATION_MANAGER"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_zones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="collection.sector",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="collection.zone",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="collection.zone",
            ),
        ),
    ]
