# Generated by Django 5.2.8 on 2026-05-07 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0002_district_remove_servicerequest_location_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="zone",
            name="collectors",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "COLLECTOR"},
                related_name="assigned_zones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
