# Generated by Django 5.2.8 on 2026-05-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin / Boss / Owner"),
                    ("SECRETARY", "Secretary / Registrar"),
                    ("GENERAL_MANAGER", "General Manager"),
                    ("LOCATION_MANAGER", "Location Manager"),
                    ("FINANCE", "Finance Officer"),
                    ("SUPERVISOR", "Supervisor"),
                    ("COLLECTOR", "Collector / Employee"),
                    ("DRIVER", "Driver"),
                    ("CUSTOMER", "Customer / Client"),
                    ("SORTING_STAFF", "Sorting / Recycling Staff"),
                ],
                default="CUSTOMER",
                max_length=20,
            ),
        ),
    ]
