# Generated by Django 5.2.8 on 2026-05-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_registrationrequest_user_is_verified_user_latitude_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
