# Generated by Django 5.2.8 on 2026-05-05 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("collection", "0001_initial"),
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WasteSorting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sorting_date", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.wastecategory",
                    ),
                ),
                (
                    "pickup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sortings",
                        to="collection.pickup",
                    ),
                ),
                (
                    "sorted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecyclingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processed_material", models.CharField(max_length=100)),
                (
                    "output_weight_kg",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("recycling_facility", models.CharField(max_length=200)),
                ("completion_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "sorting",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recycling",
                        to="recycling.wastesorting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DisposalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disposal_method", models.CharField(max_length=100)),
                ("landfill_location", models.CharField(max_length=200)),
                ("disposal_date", models.DateField()),
                ("environmental_impact_notes", models.TextField(blank=True)),
                (
                    "sorting",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disposal",
                        to="recycling.wastesorting",
                    ),
                ),
            ],
        ),
    ]
